version: '3.1'

services:

  redis:
    container_name: redis
    image: redis
    ports:
      - 6380:6380
    volumes:
      - data:/data
    entrypoint: redis-server --appendonly yes
    restart: always      

volumes:
  data:
